import _authService from './auth/authService';
import _menuService from './menu/menuService';
import _franchiseesService from './franchisees/franchiseesService';
import _initialService from './initial/initialService';
import _invoiceService from './invoice/invoiceServices';
export const authService = _authService;
export const menuService = _menuService;
export const franchiseesService = _franchiseesService;
export const initialService = _initialService;
export const invoiceService = _invoiceService;
