import mock from "./mock";
import _ from "lodash";
import Chance from "chance";

const chance = new Chance();

let transactionDB = {
    "IsSuccess": true,
    "MessageCode": 200,
    "Message": "Here is the data you requested",
    "Data": {
        "FranchiseeTransactions": [
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4290                     ",
                "Description": "STANLEY STEEMER WNY LLC - 269318",
                "ExtendedPrice": 2600.00,
                "Tax": 227.5000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2827.5000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4291                     ",
                "Description": "STANLEY STEEMER WNY LLC - 269319",
                "ExtendedPrice": 1500.00,
                "Tax": 131.2500,
                "Fees": 0.0000,
                "TotalTrxAmount": 1631.2500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4292                     ",
                "Description": "STANLEY STEEMER WNY LLC - 269320",
                "ExtendedPrice": 1750.00,
                "Tax": 153.1300,
                "Fees": 0.0000,
                "TotalTrxAmount": 1903.1300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4293                     ",
                "Description": "STANLEY STEEMER WNY LLC - 269322",
                "ExtendedPrice": 1750.00,
                "Tax": 153.1300,
                "Fees": 0.0000,
                "TotalTrxAmount": 1903.1300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4294                     ",
                "Description": "STANLEY STEEMER WNY LLC - 270424",
                "ExtendedPrice": 1550.00,
                "Tax": 135.6300,
                "Fees": 0.0000,
                "TotalTrxAmount": 1685.6300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4295                     ",
                "Description": "STANLEY STEEMER WNY LLC - 270453",
                "ExtendedPrice": 725.00,
                "Tax": 63.4400,
                "Fees": 0.0000,
                "TotalTrxAmount": 788.4400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4296                     ",
                "Description": "STANLEY STEEMER WNY LLC - 271011",
                "ExtendedPrice": 1350.00,
                "Tax": 118.1300,
                "Fees": 0.0000,
                "TotalTrxAmount": 1468.1300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4297                     ",
                "Description": "STANLEY STEEMER WNY LLC - 271012",
                "ExtendedPrice": 1725.00,
                "Tax": 150.9400,
                "Fees": 0.0000,
                "TotalTrxAmount": 1875.9400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4298                     ",
                "Description": "STANLEY STEEMER WNY LLC - 271013",
                "ExtendedPrice": 900.00,
                "Tax": 78.7500,
                "Fees": 0.0000,
                "TotalTrxAmount": 978.7500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4299                     ",
                "Description": "STANLEY STEEMER WNY LLC - 271014",
                "ExtendedPrice": 700.00,
                "Tax": 61.2500,
                "Fees": 0.0000,
                "TotalTrxAmount": 761.2500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4300                     ",
                "Description": "ADMAR SUPPLY CO INC - 19321304-0001 - SKIDSTEER",
                "ExtendedPrice": 33.60,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 33.6000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4301                     ",
                "Description": "ADMAR SUPPLY CO INC - 19321304-0001 - SKIDSTEER",
                "ExtendedPrice": 314.41,
                "Tax": 27.5100,
                "Fees": 0.0000,
                "TotalTrxAmount": 341.9200,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4302                     ",
                "Description": "ADMAR SUPPLY CO INC - 1932527-0001 - FLOOR SCRUBBER",
                "ExtendedPrice": 2950.00,
                "Tax": 258.1300,
                "Fees": 0.0000,
                "TotalTrxAmount": 3208.1300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4303                     ",
                "Description": "ADMAR SUPPLY CO INC - 1932527-0001 - FLOOR SCRUBBER",
                "ExtendedPrice": 333.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 333.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4287                     ",
                "Description": "UNITED RENTALS - 155091239-008  - FORKLIFT RENTAL",
                "ExtendedPrice": 1053.89,
                "Tax": 92.2200,
                "Fees": 0.0000,
                "TotalTrxAmount": 1146.1100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/17/2018",
                "Number": "4307                     ",
                "Description": "UNITED RENTALS - 160833920-002 - FLOOR SCRUBBER",
                "ExtendedPrice": 2530.00,
                "Tax": 221.3800,
                "Fees": 0.0000,
                "TotalTrxAmount": 2751.3800,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 67918.32,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 67918.3200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 98938.92,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 98938.9200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "10/03/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 31336.89,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 31336.8900,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "10/18/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 3237.75,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3237.7500,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "10/25/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 2953.86,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2953.8600,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4325                     ",
                "Description": "UNITED RENTALS - 155091239-009  - FORKLIFT RENTAL",
                "ExtendedPrice": 1053.89,
                "Tax": 92.2200,
                "Fees": 0.0000,
                "TotalTrxAmount": 1146.1100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": null,
                "TrxDate": "11/01/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 1029.37,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1029.3700,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/21/2018",
                "Number": "4334                     ",
                "Description": "UNITED RENTALS - 160833920-003 - FLOOR SCRUBBER",
                "ExtendedPrice": 2530.00,
                "Tax": 221.3800,
                "Fees": 0.0000,
                "TotalTrxAmount": 2751.3800,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701011",
                "Name": "KMBURNS, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/21/2018",
                "Number": "4338                     ",
                "Description": "UNITED RENTALS - 155091239-010  - FORKLIFT RENTAL",
                "ExtendedPrice": 103.50,
                "Tax": 9.0600,
                "Fees": 0.0000,
                "TotalTrxAmount": 112.5600,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMTD",
                "TrxDate": "11/21/2018",
                "Number": "4119                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774623",
                "ExtendedPrice": 70.40,
                "Tax": 6.1600,
                "Fees": 0.0000,
                "TotalTrxAmount": 76.5600,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/21/2018",
                "Number": "4335                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774622",
                "ExtendedPrice": 264.97,
                "Tax": 23.1800,
                "Fees": 0.0000,
                "TotalTrxAmount": 288.1500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": null,
                "TrxDate": "11/08/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 174.04,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 174.0400,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": null,
                "TrxDate": "11/15/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 395.19,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 395.1900,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4320                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772802",
                "ExtendedPrice": 198.47,
                "Tax": 17.3700,
                "Fees": 0.0000,
                "TotalTrxAmount": 215.8400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMTD",
                "TrxDate": "11/09/2018",
                "Number": "4117                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772801",
                "ExtendedPrice": 10.78,
                "Tax": 0.9400,
                "Fees": 0.0000,
                "TotalTrxAmount": 11.7200,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4321                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772800",
                "ExtendedPrice": 3.50,
                "Tax": 0.3100,
                "Fees": 0.0000,
                "TotalTrxAmount": 3.8100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/12/2018",
                "Number": "4322                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773788",
                "ExtendedPrice": 290.06,
                "Tax": 25.3800,
                "Fees": 0.0000,
                "TotalTrxAmount": 315.4400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMTD",
                "TrxDate": "11/09/2018",
                "Number": "4118                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773193",
                "ExtendedPrice": 20.97,
                "Tax": 1.8300,
                "Fees": 0.0000,
                "TotalTrxAmount": 22.8000,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4323                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773194",
                "ExtendedPrice": 98.42,
                "Tax": 8.6100,
                "Fees": 0.0000,
                "TotalTrxAmount": 107.0300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4324                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773192",
                "ExtendedPrice": 13.56,
                "Tax": 1.1900,
                "Fees": 0.0000,
                "TotalTrxAmount": 14.7500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 4644.56,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 4644.5600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 5808.78,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 5808.7800,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701013",
                "Name": "JIM DEVORE \u0026 ASSOCIATES, LLC",
                "TrxType": "FMT",
                "TrxDate": "10/19/2018",
                "Number": "4309                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772175",
                "ExtendedPrice": 33.78,
                "Tax": 2.9600,
                "Fees": 0.0000,
                "TotalTrxAmount": 36.7400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701019",
                "Name": "THE REGNET ENTERPRISE, LLC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 2636.19,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2636.1900,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701019",
                "Name": "THE REGNET ENTERPRISE, LLC",
                "TrxType": null,
                "TrxDate": "10/03/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 1897.92,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1897.9200,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701019",
                "Name": "THE REGNET ENTERPRISE, LLC",
                "TrxType": null,
                "TrxDate": "11/15/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 1821.94,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1821.9400,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": "FMT",
                "TrxDate": "11/15/2018",
                "Number": "4330                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774066",
                "ExtendedPrice": 28.35,
                "Tax": 2.4800,
                "Fees": 0.0000,
                "TotalTrxAmount": 30.8300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 182.59,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 182.5900,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 263.87,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 263.8700,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": "FMT",
                "TrxDate": "10/15/2018",
                "Number": "4304                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771755",
                "ExtendedPrice": 30.07,
                "Tax": 2.6300,
                "Fees": 0.0000,
                "TotalTrxAmount": 32.7000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": "FMT",
                "TrxDate": "10/15/2018",
                "Number": "4305                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771664",
                "ExtendedPrice": 40.23,
                "Tax": 3.5200,
                "Fees": 0.0000,
                "TotalTrxAmount": 43.7500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701048",
                "Name": "JOSEPH T. SWARTZMEYER",
                "TrxType": "",
                "TrxDate": "10/16/2018",
                "Number": "701001                   ",
                "Description": "Cancel for Cancel",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 13,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": "FMT",
                "TrxDate": "10/15/2018",
                "Number": "4306                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771666",
                "ExtendedPrice": 28.73,
                "Tax": 2.5100,
                "Fees": 0.0000,
                "TotalTrxAmount": 31.2400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 631.72,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 631.7200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 1330.72,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1330.7200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": null,
                "TrxDate": "11/08/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 351.14,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 351.1400,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4326                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773234",
                "ExtendedPrice": 51.97,
                "Tax": 4.5500,
                "Fees": 0.0000,
                "TotalTrxAmount": 56.5200,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": null,
                "TrxDate": "10/11/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 1160.58,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1160.5800,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": null,
                "TrxDate": "10/18/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 1160.58,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1160.5800,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701059",
                "Name": "BOB J. GATES",
                "TrxType": "FMT",
                "TrxDate": "11/21/2018",
                "Number": "4336                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774610",
                "ExtendedPrice": 33.61,
                "Tax": 2.9400,
                "Fees": 0.0000,
                "TotalTrxAmount": 36.5500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701066",
                "Name": "TANYA SOLER",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 2544.66,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2544.6600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701066",
                "Name": "TANYA SOLER",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 2577.24,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2577.2400,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701072",
                "Name": "ANDREW GERACE",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 3999.69,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3999.6900,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701072",
                "Name": "ANDREW GERACE",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 3472.78,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3472.7800,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701072",
                "Name": "ANDREW GERACE",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "4283                     ",
                "Description": "Child Support",
                "ExtendedPrice": 357.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 357.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 38,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701074",
                "Name": "ROMEO SANTIANO",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 1836.75,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1836.7500,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701074",
                "Name": "ROMEO SANTIANO",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 1836.75,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1836.7500,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701079",
                "Name": "JAMES GREEN \u0026 GEORGE MCGEE",
                "TrxType": "FMTD",
                "TrxDate": "10/31/2018",
                "Number": "4115                     ",
                "Description": "Deposit for Negative Due Rollover ",
                "ExtendedPrice": 234.61,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 234.6100,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701083",
                "Name": "JOE KOWALSKI dba JAKS",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 5958.06,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 5958.0600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701083",
                "Name": "JOE KOWALSKI dba JAKS",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 8202.95,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 8202.9500,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701083",
                "Name": "JOE KOWALSKI dba JAKS",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4285                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771209",
                "ExtendedPrice": 113.70,
                "Tax": 9.9500,
                "Fees": 0.0000,
                "TotalTrxAmount": 123.6500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701083",
                "Name": "JOE KOWALSKI dba JAKS",
                "TrxType": "FMT",
                "TrxDate": "10/19/2018",
                "Number": "4308                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772176",
                "ExtendedPrice": 25.69,
                "Tax": 2.2500,
                "Fees": 0.0000,
                "TotalTrxAmount": 27.9400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "4284                     ",
                "Description": "Child Support",
                "ExtendedPrice": 86.53,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 86.5300,
                "Status": "Open",
                "MasterTrxTypeListId": 38,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": "",
                "TrxDate": "10/16/2018",
                "Number": "701001                   ",
                "Description": "CANCELLATION FEE - CUSTOMER # 088022",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 13,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 49.76,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 49.7600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 86.52,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 86.5200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": "FMT",
                "TrxDate": "10/31/2018",
                "Number": "4315                     ",
                "Description": "Child Support",
                "ExtendedPrice": 49.75,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 49.7500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": "FMT",
                "TrxDate": "10/31/2018",
                "Number": "701001                   ",
                "Description": "Cancellation Fee - Customer # 088029 - Cancel",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": null
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701084",
                "Name": "BAJRO HADZIC",
                "TrxType": "FMT",
                "TrxDate": "10/31/2018",
                "Number": "701001                   ",
                "Description": "Cancellation Fee - Customer # 702014 - Cancel",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": null
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701085",
                "Name": "CRYSTAL FORD",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 3364.91,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3364.9100,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701085",
                "Name": "CRYSTAL FORD",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 3366.41,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3366.4100,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 3049.96,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3049.9600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 4525.42,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 4525.4200,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": "",
                "TrxDate": "10/16/2018",
                "Number": "701001                   ",
                "Description": "Cancel for Cancel",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 13,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/30/2018",
                "Number": "701001                   ",
                "Description": "Cancellation Fee - Customer # 088033 - Cancel",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": null
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": null,
                "TrxDate": "11/08/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 684.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 684.0000,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": null,
                "TrxDate": "10/11/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 42.32,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 42.3200,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701088",
                "Name": "CONNOR \u0026 SON, LLC",
                "TrxType": "FMTD",
                "TrxDate": "10/31/2018",
                "Number": "4116                     ",
                "Description": "Reverse Cancellation fee ",
                "ExtendedPrice": 50.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 50.0000,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701092",
                "Name": "BASMAR CORPORATION",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 242.56,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 242.5600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701092",
                "Name": "BASMAR CORPORATION",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 1096.13,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 1096.1300,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701094",
                "Name": "JOHNNY ROBINSON",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 7106.76,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 7106.7600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701094",
                "Name": "JOHNNY ROBINSON",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 9516.93,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 9516.9300,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701101",
                "Name": "WILLIAM BROWN, JR.",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 207.57,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 207.5700,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701101",
                "Name": "WILLIAM BROWN, JR.",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 207.57,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 207.5700,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701103",
                "Name": "TAINE S. NOWAK",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 2854.50,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2854.5000,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701103",
                "Name": "TAINE S. NOWAK",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 3438.75,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 3438.7500,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 23656.48,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 23656.4800,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4288                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 770531",
                "ExtendedPrice": 435.49,
                "Tax": 38.1100,
                "Fees": 0.0000,
                "TotalTrxAmount": 473.6000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "10/25/2018",
                "Number": "4312                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772575",
                "ExtendedPrice": 137.56,
                "Tax": 12.0400,
                "Fees": 0.0000,
                "TotalTrxAmount": 149.6000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "10/25/2018",
                "Number": "4313                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772574",
                "ExtendedPrice": 325.98,
                "Tax": 28.5200,
                "Fees": 0.0000,
                "TotalTrxAmount": 354.5000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": null,
                "TrxDate": "10/11/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 17254.49,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 17254.4900,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": null,
                "TrxDate": "10/31/2018",
                "Number": "4316                     ",
                "Description": "Payment 4 of 6 for advance check 90011306 ( 2 left) ",
                "ExtendedPrice": 6666.67,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 6666.6700,
                "Status": "Open",
                "MasterTrxTypeListId": 30,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": null,
                "TrxDate": "10/31/2018",
                "Number": "4317                     ",
                "Description": "Interest 4 of 6 for advance check ( 2 left) ",
                "ExtendedPrice": 203.84,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 203.8400,
                "Status": "Open",
                "MasterTrxTypeListId": 30,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": null,
                "TrxDate": "11/08/2018",
                "Number": "                         ",
                "Description": "TAR - Charge Back Paid",
                "ExtendedPrice": 15378.55,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 15378.5500,
                "Status": "Completed",
                "MasterTrxTypeListId": 27,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4327                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773002",
                "ExtendedPrice": 51.56,
                "Tax": 4.5100,
                "Fees": 0.0000,
                "TotalTrxAmount": 56.0700,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "11/15/2018",
                "Number": "4331                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773896",
                "ExtendedPrice": 24.00,
                "Tax": 2.1000,
                "Fees": 0.0000,
                "TotalTrxAmount": 26.1000,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701106",
                "Name": "JACKSON 4 JACKSON, INC.",
                "TrxType": "FMT",
                "TrxDate": "11/15/2018",
                "Number": "4332                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 773897",
                "ExtendedPrice": 85.90,
                "Tax": 7.5200,
                "Fees": 0.0000,
                "TotalTrxAmount": 93.4200,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4328                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772803",
                "ExtendedPrice": 666.87,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 666.8700,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "11/09/2018",
                "Number": "4329                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 772661",
                "ExtendedPrice": 70.52,
                "Tax": 6.1700,
                "Fees": 0.0000,
                "TotalTrxAmount": 76.6900,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": null,
                "TrxDate": "10/31/2018",
                "Number": "4318                     ",
                "Description": "Payment 3 of 6 for advance check 90011332 ( 3 left) ",
                "ExtendedPrice": 6666.67,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 6666.6700,
                "Status": "Open",
                "MasterTrxTypeListId": 30,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": null,
                "TrxDate": "10/31/2018",
                "Number": "4319                     ",
                "Description": "Interest 3 of 6 for Advance check 90011332 (3 left) ",
                "ExtendedPrice": 271.78,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 271.7800,
                "Status": "Open",
                "MasterTrxTypeListId": 30,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "11/21/2018",
                "Number": "4337                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774624",
                "ExtendedPrice": 170.86,
                "Tax": 14.9500,
                "Fees": 0.0000,
                "TotalTrxAmount": 185.8100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "11/26/2018",
                "Number": "4339                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774788",
                "ExtendedPrice": 695.06,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 695.0600,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMTD",
                "TrxDate": "10/22/2018",
                "Number": "4113                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771208",
                "ExtendedPrice": 203.61,
                "Tax": 17.8200,
                "Fees": 0.0000,
                "TotalTrxAmount": 221.4300,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMTD",
                "TrxDate": "10/22/2018",
                "Number": "4114                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 770407",
                "ExtendedPrice": 24.97,
                "Tax": 2.1800,
                "Fees": 0.0000,
                "TotalTrxAmount": 27.1500,
                "Status": "Open",
                "MasterTrxTypeListId": 20,
                "AmountTypelistId": 1
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "10/22/2018",
                "Number": "4310                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 770407",
                "ExtendedPrice": 24.97,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 24.9700,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "10/22/2018",
                "Number": "4311                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771208",
                "ExtendedPrice": 203.61,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 203.6100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4289                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 770407",
                "ExtendedPrice": 24.97,
                "Tax": 2.1800,
                "Fees": 0.0000,
                "TotalTrxAmount": 27.1500,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": "FMT",
                "TrxDate": "10/10/2018",
                "Number": "4286                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 771208",
                "ExtendedPrice": 203.61,
                "Tax": 17.8200,
                "Fees": 0.0000,
                "TotalTrxAmount": 221.4300,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 44922.39,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 44922.3900,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701107",
                "Name": "ANITA ALVORD D/B/A AMA ENT.",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 23720.54,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 23720.5400,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701110",
                "Name": "LEHMAN CORP.",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 5623.03,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 5623.0300,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701110",
                "Name": "LEHMAN CORP.",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 5179.16,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 5179.1600,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701114",
                "Name": "SCED LAND CO., LLC",
                "TrxType": "FMT",
                "TrxDate": "11/19/2018",
                "Number": "4333                     ",
                "Description": "Sub Contract service ",
                "ExtendedPrice": 23384.24,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 23384.2400,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701115",
                "Name": "RASOOLI, LLC",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 2427.08,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2427.0800,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701115",
                "Name": "RASOOLI, LLC",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 2427.08,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 2427.0800,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701116",
                "Name": "ABATIS, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/26/2018",
                "Number": "4340                     ",
                "Description": "DOBMEIER JANITORIAL SUPPLY INC - 774787",
                "ExtendedPrice": 39.18,
                "Tax": 3.4300,
                "Fees": 0.0000,
                "TotalTrxAmount": 42.6100,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701116",
                "Name": "ABATIS, LLC",
                "TrxType": "FMT",
                "TrxDate": "11/26/2018",
                "Number": "4341                     ",
                "Description": "NEGATIVE DUE ROLLOVER PAYMENT 1 OF 2",
                "ExtendedPrice": 473.48,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 473.4800,
                "Status": "Open",
                "MasterTrxTypeListId": 14,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701ZZB",
                "Name": "JANI-KING BUFFALO - BILLS",
                "TrxType": null,
                "TrxDate": "10/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for September 2018",
                "ExtendedPrice": 5160.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 5160.0000,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            },
            {
                "Region": "BUF",
                "FranchiseeNo": "701ZZB",
                "Name": "JANI-KING BUFFALO - BILLS",
                "TrxType": null,
                "TrxDate": "11/09/2018",
                "Number": "                         ",
                "Description": "Due Franchisee for October 2018",
                "ExtendedPrice": 10320.00,
                "Tax": 0.0000,
                "Fees": 0.0000,
                "TotalTrxAmount": 10320.0000,
                "Status": "Completed",
                "MasterTrxTypeListId": 25,
                "AmountTypelistId": 2
            }
        ]
    }
};

const FranchiseeTransactions = transactionDB.Data.FranchiseeTransactions;
let newFranchiseeTransactions = FranchiseeTransactions.map(f=>{
    let key = chance.guid();
    return {key: key, ...f}
});
transactionDB.Data.FranchiseeTransactions = newFranchiseeTransactions;


/**
 * Read Tranaction DB
 */
mock.onGet("/api/transactions/gets").reply(() => {
    return [200, transactionDB];
});

/**
 * Add new Tranaction
 */
mock.onPost("/api/transactions/save").reply(request => {
    const data = JSON.parse(request.data);
    let transaction = null;

    transactionDB = transactionDB.map(_transaction => {
        if (_transaction.Id === data.id) {
            transaction = data;
            return transaction;
        }
        return _transaction;
    });

    if (!transaction) {
        transaction = data;
        transactionDB = [...transactionDB, transaction];
    }

    return [200, transaction];
});

/**
 *  Update a Tranaction
 */
mock.onPost("/api/transactions/update").reply(request => {
    const data = JSON.parse(request.data);
    let transactions = data.transactions;
    let update = data.data;
    transactions = transactions.map(_transaction => {
        if (_transaction.Id === data.id) {
            return _.merge(_transaction, update);
        }
        return _transaction;
    });

    return [200, transactions];
});

/**
 *  Delete a invoice
 */
mock.onPost('/api/transactions/remove').reply((req) => {
    let data = JSON.parse(req.data);
    let transactions = data.transactions;
    _.remove(transactions.Data, function(_transaction) {
        return _transaction.Id === data.id;
    });

    return [200, transactions];
});

mock.onGet("/api/transactions/get").reply(request => {
    const { editId } = request.params;
    const response = _.find(transactionDB, { id: editId });
    return [200, response];
});
