const menuOptions =  [
    {
        "MenuId": 708,
        "Title": "Corporate Accounting",
        "TabName": "Corporate Accounting",
        "Slug": "corporate-accounting",
        "IframeUrl": "na",
        "Icon": "exposure",
        "IconMobile": "exposure",
        "Level": 1,
        "Type": "collapse",
        "Children": []
    },
    {
        "MenuId": 691,
        "Title": "Accounts Receivable",
        "TabName": "Accounts Receivable",
        "Slug": "accounts-receivable",
        "IframeUrl": "https://fmsplus.jkdev.com/accounts-receivable",
        "Icon": "account_balance",
        "IconMobile": "account-balance",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 692,
                "AppId": 0,
                "Title": "Invoices",
                "TabName": "Invoices",
                "Slug": "accounts-receivable/invoices",
                "IframeUrl": "https://fmsplus.jkdev.com/accounts-receivable/invoices",
                "ParentId": 691,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 693,
                "AppId": 0,
                "Title": "Bill Run",
                "TabName": "Bill Run",
                "Slug": "accounts-receivable/bill-run",
                "IframeUrl": "https://fmsplus.jkdev.com/accounts-receivable/bill-run",
                "ParentId": 691,
                "MenuLevel": 2,
                "MenuOrder": 3,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 724,
                "AppId": 0,
                "Title": "Payments",
                "TabName": "Payments",
                "Slug": "accounts-receivable/payments",
                "IframeUrl": "na",
                "ParentId": 691,
                "MenuLevel": 2,
                "MenuOrder": 4,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 1726,
        "Title": "Activity",
        "TabName": "Activity",
        "Slug": "activity",
        "IframeUrl": "na",
        "Icon": "visibility",
        "IconMobile": "visibility",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 1728,
                "AppId": 0,
                "Title": "Verifications",
                "TabName": "Verifications",
                "Slug": "activity/verifications",
                "IframeUrl": "na",
                "ParentId": 1726,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 711,
        "Title": "Accounts Payable",
        "TabName": "Accounts Payable",
        "Slug": "accounts-payable",
        "IframeUrl": "na",
        "Icon": "how_to_vote",
        "IconMobile": "how-to-vote",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 718,
                "AppId": 0,
                "Title": "Vendors",
                "TabName": "Vendors",
                "Slug": "accounts-payable/vendors",
                "IframeUrl": "na",
                "ParentId": 711,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 385,
        "Title": "Franchisees",
        "TabName": "Franchisees",
        "Slug": "franchisees",
        "IframeUrl": "https://fmsplus.jkdev.com/franchisees",
        "Icon": "location_city",
        "IconMobile": "location-city",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 707,
                "AppId": 0,
                "Title": "Franchisee List",
                "TabName": "Franchisees",
                "Slug": "franchisees/list",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/list",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": " ",
                "IconMobile": " ",
                "Type": "item"
            },
            {
                "MenuId": 386,
                "AppId": 0,
                "Title": "Transactions",
                "TabName": "Transactions",
                "Slug": "franchisees/transactions",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/transactions",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 3,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 387,
                "AppId": 0,
                "Title": "Leases",
                "TabName": "Leases",
                "Slug": "franchisees/leases",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/leases",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 4,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 712,
                "AppId": 0,
                "Title": "Finders Fees",
                "TabName": "Finders Fees",
                "Slug": "franchisees/findersfees",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 5,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 713,
                "AppId": 0,
                "Title": "Charge Backs",
                "TabName": "Charge Backs",
                "Slug": "franchisees/chargebacks",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 6,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 714,
                "AppId": 0,
                "Title": "Charge Back TAR",
                "TabName": "Charge Back TAR",
                "Slug": "franchisees/chargebacks/tar",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 7,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 715,
                "AppId": 0,
                "Title": "Negative Dues",
                "TabName": "Negative Dues",
                "Slug": "franchisees/negativedues",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 8,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 389,
                "AppId": 0,
                "Title": "Distributions",
                "TabName": "Distributions",
                "Slug": "franchisees/distributions",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/distributions",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 9,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 506,
                "AppId": 0,
                "Title": "End of Month",
                "TabName": "End of Month",
                "Slug": "franchisees/end-of-month",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 10,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 721,
                "AppId": 0,
                "Title": "Franchisee Reports",
                "TabName": "Franchisee Reports",
                "Slug": "franchisees/reports",
                "IframeUrl": "na",
                "ParentId": 385,
                "MenuLevel": 2,
                "MenuOrder": 11,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 636,
        "Title": "Customers",
        "TabName": "Customers",
        "Slug": "customers",
        "IframeUrl": "https://fmsplus.jkdev.com/customers",
        "Icon": "card_membership",
        "IconMobile": "card-membership",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 710,
                "AppId": 0,
                "Title": "Customer List",
                "TabName": "Customers",
                "Slug": "customers/list",
                "IframeUrl": "https://fmsplus.jkdev.com/franchisees/end-of-month",
                "ParentId": 636,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 685,
                "AppId": 0,
                "Title": "Contracts",
                "TabName": "Contracts",
                "Slug": "customers/contracts",
                "IframeUrl": "https://fmsplus.jkdev.com/customers/contracts",
                "ParentId": 636,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 694,
        "Title": "Customer Service",
        "TabName": "Customer Service",
        "Slug": "customer-service",
        "IframeUrl": "https://fmsplus.jkdev.com/customer-service",
        "Icon": "ring_volume",
        "IconMobile": "phone",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 725,
                "AppId": 0,
                "Title": "Customers",
                "TabName": "Customers",
                "Slug": "customer-service/customers",
                "IframeUrl": "na",
                "ParentId": 694,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 696,
                "AppId": 0,
                "Title": "Call List",
                "TabName": "Call List",
                "Slug": "customer-service/call-list",
                "IframeUrl": "https://fmsplus.jkdev.com/customer-service/call-list",
                "ParentId": 694,
                "MenuLevel": 2,
                "MenuOrder": 3,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 695,
                "AppId": 0,
                "Title": "Cases",
                "TabName": "Cases",
                "Slug": "customer-service/cases",
                "IframeUrl": "https://fmsplus.jkdev.com/customer-service/cases",
                "ParentId": 694,
                "MenuLevel": 2,
                "MenuOrder": 4,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 383,
        "Title": "Regions",
        "TabName": "Regions",
        "Slug": "regions",
        "IframeUrl": "https://fmsplus.jkdev.com/regions",
        "Icon": "language",
        "IconMobile": "language",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 384,
                "AppId": 0,
                "Title": "Territories",
                "TabName": "Territories",
                "Slug": "regions/territories",
                "IframeUrl": "https://fmsplus.jkdev.com/regions/territories",
                "ParentId": 383,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 686,
        "Title": "Sales",
        "TabName": "Sales",
        "Slug": "sales",
        "IframeUrl": "https://fmsplus.jkdev.com/sales",
        "Icon": "gamepad",
        "IconMobile": "gamepad",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 687,
                "AppId": 0,
                "Title": "Call List",
                "TabName": "Call List",
                "Slug": "sales/call-list",
                "IframeUrl": "https://fmsplus.jkdev.com/sales/call-list",
                "ParentId": 686,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 690,
                "AppId": 0,
                "Title": "Leads",
                "TabName": "Leads",
                "Slug": "sales/leads",
                "IframeUrl": "https://fmsplus.jkdev.com/sales/leads",
                "ParentId": 686,
                "MenuLevel": 2,
                "MenuOrder": 3,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 697,
        "Title": "Operations",
        "TabName": "Operations",
        "Slug": "operations",
        "IframeUrl": "https://fmsplus.jkdev.com/operations",
        "Icon": "build",
        "IconMobile": "build",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 716,
                "AppId": 0,
                "Title": "Business Offerings",
                "TabName": "Business Offerings",
                "Slug": "operations/business-offerings",
                "IframeUrl": "na",
                "ParentId": 697,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 717,
                "AppId": 0,
                "Title": "Account Walk-Thrus",
                "TabName": "Account Walk-Thrus",
                "Slug": "operations/account-walk-thrus",
                "IframeUrl": "na",
                "ParentId": 697,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            },
            {
                "MenuId": 698,
                "AppId": 0,
                "Title": "Inspections",
                "TabName": "Inspections",
                "Slug": "operations/inspections",
                "IframeUrl": "https://fmsplus.jkdev.com/operations/inspections",
                "ParentId": 697,
                "MenuLevel": 2,
                "MenuOrder": 4,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 699,
        "Title": "Comissions",
        "TabName": "Comissions",
        "Slug": "comissions",
        "IframeUrl": "https://fmsplus.jkdev.com/comissions",
        "Icon": "monetization_on",
        "IconMobile": "monetization-on",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 700,
                "AppId": 0,
                "Title": "Plans",
                "TabName": "Plans",
                "Slug": "comissions/plans",
                "IframeUrl": "https://fmsplus.jkdev.com/comissions/plans",
                "ParentId": 699,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    },
    {
        "MenuId": 719,
        "Title": "Social Media",
        "TabName": "Social Media",
        "Slug": "social-media",
        "IframeUrl": "na",
        "Icon": "portrait",
        "IconMobile": "portrait",
        "Level": 1,
        "Type": "collapse",
        "Children": []
    },
    {
        "MenuId": 720,
        "Title": "Settings",
        "TabName": "Settings",
        "Slug": "settings",
        "IframeUrl": "na",
        "Icon": "vertical_split",
        "IconMobile": "settings",
        "Level": 1,
        "Type": "collapse",
        "Children": [
            {
                "MenuId": 1725,
                "AppId": 0,
                "Title": "Users",
                "TabName": "Users",
                "Slug": "settings/users",
                "IframeUrl": "na",
                "ParentId": 720,
                "MenuLevel": 2,
                "MenuOrder": 2,
                "Icon": "",
                "IconMobile": "",
                "Type": "item"
            }
        ]
    }
];

export default menuOptions;